### ISSUE TITLE
проблема с плагином

### ISSUE THREAD

**Issue by alexeiionow** [ortuz/ADSCoreLite#2]
Добрый день, Такая проблема с плагином: при показе рекламы на телефоне, открывается дополнительное окно приложения - см фото 001. Данное окно неактивно, т.е. в него нельзя перейти. Устанавливал все по инструкции, версия unreal 5.2.1 на чистом проекте. И при каждом следующем показе рекламы эти окна множатся. При закрытии приложения, эти окна остаются. Это так должно быть или что-то неправильно работает?
![001](https://github.com/ortuz/ADSCoreLite/assets/147520697/c7dedb6f-7661-4a91-be30-042f38299eff)
![002](https://github.com/ortuz/ADSCoreLite/assets/147520697/51e1fc50-acf2-4b3c-a831-4d5e7db5c712)

**Comment by voidrosegd** [comment]
Проблема будет решена при переходе на новую версию РСЯ.
